services:
  studypeer:
    container_name: studypeer
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      WATCHFILES_FORCE_POLLING: "true"
    command: sh -c 'flask --app run.py run --host=0.0.0.0 --port=$${PORT:-5001} --reload'
    restart: unless-stopped
